name: podman_backup
description: A small dart tool to push regular backups of podman volumes to a remote.
homepage: https://github.com/Skycoder42/podman_backup
version: 1.2.1
publish_to: none

environment:
  sdk: ^3.0.0

platforms:
  linux:

executables:
  podman-backup: podman_backup

dependencies:
  args: ^2.4.2
  build_cli_annotations: ^2.1.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  posix: ^5.0.0
  riverpod: ^2.3.6
  rxdart: ^0.27.7

dev_dependencies:
  build_cli: ^2.2.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  dart_pre_commit: ^5.2.0+1
  dart_test_tools: ^5.3.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  pubspec_generator: ^3.0.1
  test: ^1.24.6

aur:
  maintainer: Skycoder42 <Skycoder42@users.noreply.github.com>
  license: BSD
  depends:
    - podman
    - xz
    - systemd
  testArgs: --preset unit
  makedeb:
    depends:
      - podman
      - xz-utils
      - systemd

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/podman_backup/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/podman_backup/compare/v%from%...v%to%
