name: podman_backup
description: A small dart tool to push regular backups of podman volumes to a remote.
homepage: https://github.com/Skycoder42/podman_backup
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

platforms:
  linux:

executables:
  podman-backup: podman_backup

dependencies:
  args: ^2.4.0
  build_cli_annotations: ^2.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  logging: ^1.1.1
  meta: ^1.9.1
  riverpod: ^2.3.6

dev_dependencies:
  build_cli: ^2.2.1
  build_runner: ^2.3.3
  dart_pre_commit: ^4.1.0
  dart_test_tools: ^4.9.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  pubspec_generator: ^3.0.1
  test: ^1.24.2
  tuple: ^2.0.1

aur:
  maintainer: Skycoder42 <Skycoder42@users.noreply.github.com>
  license: BSD
  depends:
    - podman
    - xz
    - systemd
  testArgs: --preset unit
  makedeb:
    depends:
      - podman
      - xz-utils
      - systemd

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/podman_backup/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/podman_backup/compare/v%from%...v%to%
