name: podman_backup
description: A small dart tool to push regular backups of podman volumes to a remote.
homepage: https://github.com/Skycoder42/podman_backup
version: 1.3.5
publish_to: none

environment:
  sdk: ^3.7.0

platforms:
  linux:

executables:
  podman-backup: podman_backup

dependencies:
  args: ^2.7.0
  build_cli_annotations: ^2.1.0
  collection: ^1.19.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  posix: ^6.0.1
  riverpod: ^2.6.1
  rxdart: ^0.28.0

dev_dependencies:
  build_cli: ^2.2.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  dart_pre_commit: ^6.0.0
  dart_test_tools: ^6.1.1
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  test: ^1.25.15

aur:
  maintainer: Skycoder42 <Skycoder42@users.noreply.github.com>
  license: BSD
  depends:
    - podman
    - xz
    - systemd
  makedeb:
    depends:
      - podman
      - xz-utils
      - systemd

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/podman_backup/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/podman_backup/compare/v%from%...v%to%
