name: podman_backup
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  dart_pre_commit: ^4.1.0
  dart_test_tools: ^4.8.0
  test: ^1.23.1
