name: podman_backup
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

executables:
  podman-backup: podman_backup

dependencies:
  args: ^2.4.0
  build_cli_annotations: ^2.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  logging: ^1.1.1
  meta: ^1.9.1
  riverpod: ^2.3.2

dev_dependencies:
  build_cli: ^2.2.1
  build_runner: ^2.3.3
  cider: ^0.1.4
  dart_pre_commit: ^4.1.0
  dart_test_tools: ^4.8.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  pubspec_generator: ^3.0.1
  test: ^1.24.0
  tuple: ^2.0.1

dart_pre_commit:
  flutter-compat: false
