name: Continuous integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      buildRunner: true
      extendedAnalyzerArgs: --linter test-import # Do not run the lib-export linter
      unitTestPaths: -P unit
      coverageExclude: >-
        "**/*.freezed.dart"
        "**/*.g.dart"
      integrationTestPaths: -P integration
      integrationTestSetup: >-
        {
          "linux": "./tool/integration-test-setup.sh"
        }

  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    with:
      buildRunner: true

  aur:
    name: AUR
    needs:
      - cd
    uses: Skycoder42/dart_test_tools/.github/workflows/aur.yml@main
    with:
      createAurUpdate: ${{ needs.cd.outputs.releaseCreated == 'true' }}
    secrets:
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
